# Generated by Django 6.0.6 on 2026-06-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in Tanzanian Shillings (Tshs)', max_digits=12, max_length=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('PHONE', 'Phone Payment')], default='CASH', max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
