# Generated by Django 6.0.6 on 2026-06-22 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('MAIN', 'Main Branch'), ('SWAHILI', 'Swahili Branch'), ('MULAGO', 'Mulago Branch'), ('MSIMBAZI', 'Msimbazi Branch'), ('BIGONE', 'Big One Branch'), ('GONGOLAMBOTO', 'Gongo La Mboto Branch')], default='MAIN', help_text='Branch where this sale was recorded', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in Tanzanian Shillings (Tshs)', max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('PHONE', 'Phone Payment')], default='CASH', max_length=5)),
                ('description', models.CharField(blank=True, help_text='Optional description or note', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accountant', models.ForeignKey(help_text='The accountant who recorded this sale', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-timestamp'],
            },
        ),
    ]
