# Generated by Django 6.0.6 on 2026-06-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='branch',
            field=models.CharField(choices=[('MAIN', 'Main Branch'), ('SWAHILI', 'Swahili Branch'), ('MULAGO', 'Mulago Branch'), ('MSIMBAZI', 'Msimbazi Branch'), ('BIGONE', 'Big One Branch'), ('GONGOLAMBOTO', 'Gongo La Mboto Branch')], default='MAIN', max_length=12),
        ),
    ]
